- name: add Mercurial yum repo
  become: yes
  yum_repository:
    name: mercurial.selenic.com
    description: Mercurial
    baseurl: https://www.mercurial-scm.org/release/centos7/
    gpgcheck: no

- name: install dev programs to compile cloud-provider-openstack
  become: yes
  yum:
    disable_gpg_check: yes
    state: present
    name:
      - git
      - python-devel
      - gcc
      - gcc-c++
      - kernel-devel
      - mercurial
      - python-pip

- name: ensure go module source directories exist
  file:
    path: /home/centos/go/src
    state: directory

## Partner NFS CSI plugin
- name: get the k8s-csi/csi-driver-nfs repository
  git:
    repo: 'https://github.com/kubernetes-csi/csi-driver-nfs.git'
    dest: /home/centos/go/src/github.com/kubernetes-csi/csi-driver-nfs
    update: no

- name: check if docker nfsplugin image exists
  command: docker images -q nfsplugin
  register: docker_nfsplugin_image_id

- name: make the nfsplugin image and push it to the local registry
  shell: |
    source /etc/profile.d/golang.sh
    cd /home/centos/go/src/github.com/kubernetes-csi/csi-driver-nfs
    make container
    id=$(docker images -q nfsplugin)
    docker tag $id master.rdocloud:5000/nfsplugin
    docker push master.rdocloud:5000/nfsplugin
  when: docker_nfsplugin_image_id.stdout == ''

## DaemonSet for csi-nodeplugin-nfsplugin

- name: deploy RBAC for csi-nodeplugin-nfsplugin
  command: kubectl apply -f csi-nodeplugin-rbac.yaml
  args:
    chdir: /home/centos/go/src/github.com/kubernetes-csi/csi-driver-nfs/deploy/kubernetes

- name: adjust csi-nodeplugin-nfsplugin.yaml to use current registrar image
  replace:
    path: /home/centos/go/src/github.com/kubernetes-csi/csi-driver-nfs/deploy/kubernetes/csi-nodeplugin-nfsplugin.yaml
    regexp: "image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.2"
    replace: "image: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0"

- name: adjust csi-nodeplugin-nfsplugin.yaml to use local docker nfsplugin image
  replace:
    path: /home/centos/go/src/github.com/kubernetes-csi/csi-driver-nfs/deploy/kubernetes/csi-nodeplugin-nfsplugin.yaml
    regexp: "image: quay.io/k8scsi/nfsplugin:v1.0.0"
    replace: "image: master.rdocloud:5000/nfsplugin"

- name: change api version for csi-nodeplugin-nfsplugin.yaml from apps/v1beta2 to apps/v1
  replace:
    path: /home/centos/go/src/github.com/kubernetes-csi/csi-driver-nfs/deploy/kubernetes/csi-nodeplugin-nfsplugin.yaml
    regexp: "apiVersion: apps/v1beta2"
    replace: "apiVersion: apps/v1"

- name: deploy csi-nodeplugin-nfsplugin DaemonSet
  command: kubectl apply -f csi-nodeplugin-nfsplugin.yaml
  args:
    chdir: /home/centos/go/src/github.com/kubernetes-csi/csi-driver-nfs/deploy/kubernetes


## Manila CSI plugin

- name: get the openstack-cloud-provider repository
  git:
    # repo: 'https://github.com/kubernetes/cloud-provider-openstack'
    repo: 'https://github.com/gman0/cloud-provider-openstack'
    version: 'csimanila-snapshots-nfs'
    dest: /home/centos/go/src/k8s.io/cloud-provider-openstack
    update: no

- name: check if docker manila-csi-plugin image exists
  command: docker images -q k8scloudprovider/manila-csi-plugin
  register: docker_manila_csi_image_id

- name: make the manila-csi image and push it to the local registry
  shell: |
    source /etc/profile.d/golang.sh
    cd /home/centos/
    # Install the go dependency management tool
    curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    cd /home/centos/go/src/k8s.io/cloud-provider-openstack
    make image-manila-csi-plugin
    id=$(docker images -q k8scloudprovider/manila-csi-plugin)
    docker tag $id master.rdocloud:5000/k8scloudprovider/manila-csi-plugin
    docker push master.rdocloud:5000/k8scloudprovider/manila-csi-plugin
  when: docker_manila_csi_image_id.stdout == ''

## Manila CSI nodeplugin daemonset

- name: deploy RBAC for manila-csi-nodeplugin
  command: kubectl apply -f csi-nodeplugin-rbac.yaml
  args:
    chdir: /home/centos/go/src/k8s.io/cloud-provider-openstack/manifests/manila-csi-plugin

- name: copy csi-nodeplugin-manilaplugin.yaml to csi-nodeplugin-manilaplugin-nfs.yaml
  command: cp csi-nodeplugin-manilaplugin.yaml csi-nodeplugin-manilaplugin-nfs.yaml
  args:
    chdir: /home/centos/go/src/k8s.io/cloud-provider-openstack/manifests/manila-csi-plugin

- name: fix volumeMounts fwd-plugin-dir
  replace:
    path: /home/centos/go/src/k8s.io/cloud-provider-openstack/manifests/manila-csi-plugin/csi-nodeplugin-manilaplugin-nfs.yaml
    after: '- name: fwd-plugin-dir'
    regexp: 'mountPath: >>>Path.*'
    replace: 'mountPath: /plugin'

- name: fix volumes hostPath fwd-plugin-dir
  replace:
    path: /home/centos/go/src/k8s.io/cloud-provider-openstack/manifests/manila-csi-plugin/csi-nodeplugin-manilaplugin-nfs.yaml
    after: 'hostPath:'
    regexp: 'path: /var/lib/kubelet/plugins/>>>The other CSI plugin<<<'
    replace: 'path: /var/lib/kubelet/plugins/csi-nfsplugin'

- name: fix MANILA_SHARE_PROTO
  replace:
    path: /home/centos/go/src/k8s.io/cloud-provider-openstack/manifests/manila-csi-plugin/csi-nodeplugin-manilaplugin-nfs.yaml
    after: '- name: MANILA_SHARE_PROTO'
    regexp: 'value: >>>Share protocol goes here<<<$'
    replace: 'value: NFS'

- name: fix FWD_CSI_ENDPOINT
  replace:
    path: /home/centos/go/src/k8s.io/cloud-provider-openstack/manifests/manila-csi-plugin/csi-nodeplugin-manilaplugin-nfs.yaml
    after: '- name: FWD_CSI_ENDPOINT'
    regexp: "value: unix://>>>Absolute path to proxy'd plugin .sock file<<<"
    replace: 'value: unix:///plugin/csi.sock'

- name: adjust csi-nodeplugin-manilaplugin-nfs.yaml to use local manilaplugin image
  replace:
    path: /home/centos/go/src/k8s.io/cloud-provider-openstack/manifests/manila-csi-plugin/csi-nodeplugin-manilaplugin-nfs.yaml
    regexp: "image: manila-csi-plugin"
    replace: "image: master.rdocloud:5000/k8scloudprovider/manila-csi-plugin"

- name: deploy csi-nodeplugin-manilaaplugin daemonSet
  command: kubectl apply -f csi-nodeplugin-manilaplugin-nfs.yaml
  args:
    chdir: /home/centos/go/src/k8s.io/cloud-provider-openstack/manifests/manila-csi-plugin

## StatefulSet for Manila CSI Provisioner

- name: deploy RBAC for manila-csi-provisioner
  command: kubectl apply -f csi-provisioner-rbac.yaml
  args:
    chdir: /home/centos/go/src/k8s.io/cloud-provider-openstack/manifests/manila-csi-plugin

- name: deploy manila-csi-provisioner stateful set
  command: kubectl apply -f csi-provisioner-manilaplugin.yaml
  args:
    chdir: /home/centos/go/src/k8s.io/cloud-provider-openstack/manifests/manila-csi-plugin

## StatefulSet for Manila CSI attacher

- name: deploy RBAC for manila-csi-attacher
  command: kubectl apply -f csi-attacher-rbac.yaml
  args:
    chdir: /home/centos/go/src/k8s.io/cloud-provider-openstack/manifests/manila-csi-plugin

- name: deploy csi-attacher-manilaplugin StatefulSet
  command: kubectl apply -f csi-attacher-manilaplugin.yaml
  args:
    chdir: /home/centos/go/src/k8s.io/cloud-provider-openstack/manifests/manila-csi-plugin

- name: generate csi-manila-nfs-secrets
  shell: |
    source /home/centos/demorc
    /home/centos/go/src/k8s.io/cloud-provider-openstack/examples/manila-provisioner/generate-secrets.sh -n csi-manila-nfs-secrets |\
    grep -v ': ""' > /home/centos/csi-manila-nfs-secrets.yaml
    kubectl apply -f /home/centos/csi-manila-nfs-secrets.yaml
