- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  vars_files:
    - keys.yml
  roles:
    - openstack_infra

- hosts: cluster
  gather_facts: false
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - cluster

- hosts: master
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - gantsign.golang
    - master
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'

- hosts: workers
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - workers

- hosts: devstack
  roles:
    - devstack
