- name: Add Mercurial yum repo
  yum_repository:
    name: mercurial.selenic.com
    description: Mercurial
    baseurl: https://www.mercurial-scm.org/release/centos7/
    gpgcheck: no

- name: install dev programs to compile cloud-provider-openstack
  yum:
    disable_gpg_check: yes
    state: present
    name:
      - git
      - python-devel
      - gcc
      - gcc-c++
      - kernel-devel
      - mercurial
      - python-pip

- name: Ensure go module source directories exist
  file:
    path: /home/centos/go/src/github.com
    state: directory

- name: Get the ceph-csi repository
  git:
    repo: 'https://github.com/ceph/ceph-csi.git'
    dest: /home/centos/go/src/github.com/ceph/
    version: master

- name: Make the cephfs image and push it to the local registry
  shell: |
    cd /home/centos/go/src/github.com/ceph/
    source /etc/profile.d/golang.sh
    make image-cephfsplugin

- name: Get the openstack-cloud-provider repository
  git:
    repo: 'https://github.com/kubernetes/cloud-provider-openstack'
    dest: /home/centos/go/src/github.com/k8s/
    refspec: '+refs/pull/*:refs/heads/*'
    version: pull/536/head:manila-csi

- name: Make the manila-csi image and push it to the local registry
  shell: |
    cd /home/centos/
    source /etc/profile.d/golang.sh
    # Install the go dependency management tool
    curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    cd /home/centos/go/src/github.com/k8s/cloud-provider-openstack
    make image-manila-csi-plugin

- name: initialize kubeadm on master
  shell: |
    kubeadm init --pod-network-cidr=10.244.0.0/16 \
        --token={{kubernetes_token }} \
        --apiserver-advertise-address={{ ansible_default_ipv4.address }} \
        --apiserver-cert-extra-sans={{ inventory_hostname }}
  args:
    creates: /etc/kubernetes/manifests/kube-apiserver.yaml

- name: create flannel network
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml

- name: get kubeconfig.conf from the master node
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: kubeconfig.conf
    flat: yes

- name: replace the master node's internal/host network IP with floating IP
  delegate_to: localhost
  become: no
  replace:
    path: '{{ playbook_dir }}/kubeconfig.conf'
    after: 'server:'
    regexp: 'https://[0-9.]+:6443'
    replace: "https://{{ inventory_hostname }}:6443"
